config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'

  root to: 'welcome#home'
  get "/auth/google_oauth2", as: :google_login
  get "/auth/google_oauth2/callback", to: 'sessions#create'
  delete "/logout", to: "sessions#destroy", as: :logout

  post "/headline", to: "welcome#generate_headline", as: :generate_headline
  post "/abstract", to: "welcome#generate_abstract", as: :generate_abstract

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, uniqueness: true

  def self.populate
    service = ArticleService.new
    service.populate_database
  end

  def self.markovify_headlines
    titles = pluck(:title)
    markov = MarkyMarkov::Dictionary.new('headlines_dictionary')
    titles.each do |title|
      markov.parse_string(title)
    end
    markov.save_dictionary!
  end

  def self.generate_headline
    markov = MarkyMarkov::Dictionary.new('headlines_dictionary')
    headline = markov.generate_n_words(rand(5..10)).delete(".")
    headline = clean_headline(headline)
  end

  def self.clean_headline(headline)
    headline = clean_ending(headline)
    if headline == "" || headline.nil?
      headline = generate_headline
    end
    headline = remove_ending_punctuation(headline)
    headline + "." unless headline.split.last.include?('?')
  end

  def self.clean_ending(headline)
    bad_words = ["the", "at", "in", "or", "of", "a", "it", "its", "it's", "on", "with", "is", "has", "and", "to", "for", "as"]
    while bad_words.include?(headline.split.last.downcase)
      headline = headline.split
      headline.pop
      headline = headline.join(' ')
    end
    headline
  end

  def self.remove_ending_punctuation(headline)
    headline = headline.chars
    headline.pop if [',',':'].include?(headline.last)
    headline.join
  end

  def self.generate_abstract
    markov = MarkyMarkov::Dictionary.new('abstract_dictionary')
    abstract = markov.generate_n_sentences(rand(3..6))
  end

  def self.markovify_abstractions
    abstractions = pluck(:abstract)
    markov = MarkyMarkov::Dictionary.new('abstract_dictionary', 3)
    abstractions.each do |abstract|
      markov.parse_string(abstract)
    end
    markov.save_dictionary!
  end
end

app/models/article_obj.rb
class ArticleObj < OpenStruct
  def self.service
    ArticleService.new
  end

  def self.all
    articles_hash = service.articles_hash[:results]
    articles_hash.map { |article| ArticleObj.new(article) }
  end

  def self.titles
    all.map { |article| article[:title] }
  end

  def self.save
    all.map do |article|
      Article.create({
        title: article[:title],
        abstract: article[:abstract],
        url: article[:url],
        section: article[:section],
      })
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user,
                :current_user_name

  def current_user
    @user ||= session[:user] if session[:user]
  end

  def current_user_name
    current_user["name"]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = request.env['omniauth.auth']['info']
    session[:user] = @user
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def generate_headline
    @headline = Article.generate_headline

    respond_to do |format|
      format.js
    end
  end

  def generate_abstract
    @abstract = Article.generate_abstract

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headlines_helper.rb
module HeadlinesHelper
end

app/helpers/markov_helper.rb
module MarkovHelper
end

app/helpers/sessions_controller_helper.rb
module SessionsControllerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCurious</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
</body>
</html>

app/views/welcome/generate_abstract.js.erb
$("#abstract").text("<%= @abstract %>");

app/views/welcome/generate_headline.js.erb
$("#headline").text("<%= @headline %>");

app/views/welcome/home.html.erb
<div class="ui left vertical inverted sidebar labeled icon menu">
  <% if current_user %>
    <%= link_to logout_path, method: :delete, class: "item" do %>
      <i class="remove user icon"></i>
      Logout
      <p><%= current_user_name %></p>
    <% end %>
  <% else %>
    <%= link_to google_login_path, class: "item" do %>
      <i class="add user icon"></i>
      Login
      <p>with Google</p>
    <% end %>
  <% end %>
</div>

<i id="sidebar-toggle" class="big sidebar link icon"></i>

<center>
  <h2>Welcome to News Generator!</h2>
  <% if current_user %>
    <div id="button">
      <%= button_to generate_headline_path, remote: true, id: "gen-button", class: "ui animated fade button" do  %>
        <div class="visible content">Generate Headline</div>
        <div class="hidden content">Click!</div>
      <% end %>
    </div>
    <div id="button">
      <%= button_to generate_abstract_path, remote: true, id: "gen-button", class: "ui animated fade button" do  %>
        <div class="visible content">Generate Abstract</div>
        <div class="hidden content">Click!</div>
      <% end %>
    </div>
  <% else %>
    <h3>Click the icon in the top left to login with Google</h3>
  <% end %>

  <h2 id="headline" class="ui container"></h2>
  <p id="abstract" class="ui container"></p>
</center>